### ISSUE TITLE
Check for missing commits vs devel

### ISSUE THREAD

**Issue by gundalow** [ansible-collections/google.cloud#166]
##### SUMMARY
The "Big Migration" has now taken place.

As this collection already exists, we need to carefully check to see if any further commits went into devel since this repo was created.

Please check the contents of https://github.com/ansible-collection-migration/google.cloud against this repo

##### ISSUE TYPE
- Bug Report

**Comment by gundalow** [comment]
Clarification:
* Please do a per-file level diff against every file in the ansible-collection-migration repo and this one
* Pay care to files added and removed.
* During the last two weeks there have been lots of fixes, especially around and tests, dependencies, and new collection features e.g. meta/action_groups.yml

**Comment by gundalow** [comment]
https://github.com/ansible-collections/ansible_collections_google/pull/167 could be an example of such a missing change.

**Comment by rambleraptor** [comment]
I've gone through the diffs and everything seems to be in order (there are changes that exist in the collection, but never upstreamed to core). 

Could you elaborate on some of the new collection features (like meta/action_groups.yml) or point me to some documentation for them?

**Comment by gundalow** [comment]
No proper docs yet, though https://github.com/ansible/ansible/issues/68383 and https://github.com/ansible/ansible/pull/67291 may help.

**Comment by toumorokoshi** [comment]
I'll close this as I believe it's outdated, but feel free to re-open if there's anything further to verify.
