### ISSUE TITLE
Missing test

### ISSUE THREAD

**Issue by felixfontein** [ansible-collections/google.cloud#227]
##### SUMMARY
For some reason, a unit test for plugins/module_utils/gcp_utils.py ended up in community.general: https://github.com/ansible-collections/community.general/blob/master/tests/unit/plugins/module_utils/gcp/test_gcp_utils.py

Do you want to move it to this collection? I think that would make more sense.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
unit tests

##### ANSIBLE VERSION
```paste below
devel
```

**Comment by rambleraptor** [comment]
That would be a great idea. Thanks!
