### ISSUE TITLE
Consider implementing Container GKE Updates for Cluster and Node Pools

### ISSUE THREAD

**Issue by imjoseangel** [ansible-collections/google.cloud#346]
##### SUMMARY

Create `gcp_container_cluster_update` and `gcp_container_node_pool_update` modules for Automatic Updates on different GKEs and Projects

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

`gcp_container_cluster_update`
`gcp_container_node_pool_update` 
##### ADDITIONAL INFORMATION

```python
credentials, project_id = google.auth.default()
authed_session = AuthorizedSession(credentials)
response = authed_session.request(
    'PUT', 'https://container.googleapis.com/v1/projects/packlink-{0}/locations/{2}/clusters/{0}/nodePools/{1}'.format(project, node, location), data=data)
print(response.json())
```

**Comment by imjoseangel** [comment]
If there are votes for this functionality, I can work on it for the next release.

**Comment by tardis4500** [comment]
Actually, the correct approach would be to correct gcp_container_cluster and gcp_container_node_pool to perform as any other Ansible module would: make any updates necessary. There should never be a reason to have one module for creation/deletion of a resource and another for the updates. That pretty much breaks the main reason for using Ansible.

**Comment by tardis4500** [comment]
This ticket should be closed as will not fix. There is already a bug submitted (#197) that gcp_container_cluster is not updating state properly on the cluster. Reading the module, it is coded to do that but for some reason is not.
