### ISSUE TITLE
How to update/contribute to this repo?

### ISSUE THREAD

**Issue by edwardsamuel** [ansible-collections/google.cloud#458]
Previously, cmiiw, we used https://github.com/GoogleCloudPlatform/magic-modules to update this repo. But looks like, we don't do it anymore.

I have a PR in https://github.com/GoogleCloudPlatform/magic-modules/pull/5163 and also a generated code in https://github.com/edwardsamuel/google.cloud/commit/314bebe2e875b85f2c8473e9609cdaf436dd37fd.

How do we move forward if we have any update for this repo?

**Comment by smemsh** [comment]
@edwardsamuel What indicates that magic modules don't eventually get merged into this repo? Are you sure it's not just that the generate and merge happens infrequently?

**Comment by toumorokoshi** [comment]
Hello! Please see https://github.com/ansible-collections/google.cloud/blob/master/CONTRIBUTING.md (new as of November).
