### ISSUE TITLE
Plugin name `gcp_compute` no longer works

### ISSUE THREAD

**Issue by gygitlab** [ansible-collections/google.cloud#536]
##### SUMMARY
After upgrading to `1.1.0` we got the following error on our builds due to an Inventory plugin name mismatch

```
Invalid value "gcp_compute" for configuration option "plugin_type: inventory
plugin: ansible_collections.google.cloud.plugins.inventory.gcp_compute setting:
plugin ", valid values are: google.cloud.gcp_compute
```

I can see this new name `google.cloud.gcp_compute` is referenced in examples but I don't see any reference to this breaking change in the release notes. There's an argument perhaps that this sort of change should've been saved for a major release also.

Was this intended?

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
`google.cloud.gcp_compute`

##### ANSIBLE VERSION

```paste below
ansible [core 2.13.6]
  config file = <redacted>/ansible/ansible.cfg
  configured module search path = ['<redacted>/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = <redacted>/.asdf/installs/python/3.10.6/lib/python3.10/site-packages/ansible
  ansible collection location = <redacted>/.ansible/collections:/usr/share/ansible/collections
  executable location = <redacted>/.asdf/installs/python/3.10.6/bin/ansible
  python version = 3.10.6 (main, Aug  4 2022, 11:58:04) [Clang 13.1.6 (clang-1316.0.21.2.5)]
  jinja version = 3.1.2
  libyaml = True
```

##### COLLECTION VERSION

```paste below
google.cloud                  1.0.2
```

##### CONFIGURATION

```paste below
plugin: gcp_compute
projects:
  - <redacted>
filters:
  - labels.gitlab_node_prefix = <redacted>
keyed_groups:
  - key: labels.<redacted>
    separator: ''
  - key: labels.<redacted>
    separator: ''
scopes:
  - https://www.googleapis.com/auth/compute
hostnames:
  # List host by name instead of the default public ip
  - name
compose:
  # Set an inventory parameter to use the Public IP address to connect to the host
  # For Private ip use "networkInterfaces[0].networkIP"
  ansible_host: networkInterfaces[0].accessConfigs[0].natIP
```

##### EXPECTED RESULTS

That the plugin name would still work in a minor release.

**Comment by gygitlab** [comment]
It's worth noting that the name change is also not backwards compatible. So `google.cloud.gcp_compute` doesn't work with versions `<1.1.0`.

**Comment by toumorokoshi** [comment]
Hello! The change was definitely not intended: the intent was minor feature improvements and no backwards incompatible changes.

We'll take a look, sorry about the issues.

**Comment by toumorokoshi** [comment]
can you try this now with the new release (1.1.2)? It should have fixed the issue (verified locally).

**Comment by gygitlab** [comment]
> can you try this now with the new release (1.1.2)? It should have fixed the issue (verified locally).

Yup that's done the trick! Many thanks for the fix and happy holidays!
