### ISSUE TITLE
`gcp_compute_route` does not update routes

### ISSUE THREAD

**Issue by nkakouros** [ansible-collections/google.cloud#542]
##### SUMMARY

`gcp_compute_route` does not update an existing route. This is a limitation of google cloud APIs. However, it should be easy to add the functionality in the module, ie delete an existing route and create a new one in place.

ISSUE TYPE
##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

gcp_compute_route

**Comment by toumorokoshi** [comment]
@nkakouros do you have an example config of it not working? The code [already deletes and creates](https://github.com/ansible-collections/google.cloud/blob/master/plugins/modules/gcp_compute_route.py#L397), and I added a test (#544) that passes.

**Comment by nkakouros** [comment]
You are right, I am closing this.
