### ISSUE TITLE
wrong version for google.cloud

### ISSUE THREAD

**Issue by Naramsim** [ansible-collections/google.cloud#550]
Hi, in the docs it's stated that the property `service_account_contents ` was _added in google.cloud 2.8.2_

There's no such version of google.cloud

```log
ERROR! Failed to resolve the requested dependencies map. Could not satisfy the following requirements:
* google.cloud:2.8.2 (direct request)
```

**Comment by toumorokoshi** [comment]
Hello! I think that version number is referring to the ansible-core version? google.cloud has been a part of the ansible-core package for a while. 

I'm not sure about removing the version just yet.. it's true the meaning is unclear, but it is in the eye of the consumer.

**Comment by Naramsim** [comment]
yeah, right now it doesn't mean anything, so I suggest you should remove it or specify that you are referring to ansible-core
