### ISSUE TITLE
IPV6 support for GKE Creation

### ISSUE THREAD

**Issue by safaci2000** [ansible-collections/google.cloud#566]
##### SUMMARY
GKE Creation, gcp_container_cluster, does not currently support an option for specifying the DataPlane.  

More context here: https://cloud.google.com/kubernetes-engine/docs/how-to/dataplane-v2.  It is required for enabling IPV6 on a GKE cluster.

##### ISSUE TYPE
- Expose the dataplane-v2 option as a configuration setting that can be set.

##### COMPONENT NAME
gcp_container_cluster

Possibly related: gcp_container_node_pool 

##### ADDITIONAL INFORMATION
I was going to attempt to fix this but I wanted to make sure that this wasn't something that I've missed.  Also any guidance is appreciated.

**Comment by toumorokoshi** [comment]
Thanks for the feature requests! PRs are welcome. As bandwidth allows I am adding new features, but primarily focused on stability and bug fixes at the moment.

**Comment by safaci2000** [comment]
PR is linked to ticket.  https://github.com/ansible-collections/google.cloud/pull/567  In case it was missed.  I've tested this against GKE by installing the collection from my fork and it seems to work as advertised, though feel free to test it further and any feedback is appreciated.

**Comment by toumorokoshi** [comment]
Feel free to close! I'll try to get a release out this week.
