### ISSUE TITLE
How often does this collection get generated from magic-modules?

### ISSUE THREAD

**Issue by d0x2f** [ansible-collections/google.cloud#581]
There are countless resources and parameters missing from this collection compared to the terraform module.

For example this PR to add a parameter was merged over a year ago but still isn't available for ansible: https://github.com/GoogleCloudPlatform/magic-modules/pull/5849.

Does it happen on a schedule, on an ad-hoc basis or is it not done at all any more?

**Comment by toumorokoshi** [comment]
Unfortunately (or fortunately, depending on how you look at it) we no longer generate from magic-modules. A majority of the modules in magic-modules that aren't present already in this collection required hand-written work to integrate. 

For now this repository is maintained separately, although we are looking at opportunities to automate this further.

**Comment by d0x2f** [comment]
Ok thanks for the clarification!
